
#remote_theme: pages-themes/leap-day@v0.2.0
remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
- jekyll-remote-theme 

title: Gwada Paddling
description: Actu des compétitions des sports de pagaie en Guadeloupe

post_search: true

social-network-links:
  rss: true
  
rss-description: Actu des compétitions des sports de pagaie en Guadeloupe

share-links-active:
  twitter: true
  facebook: true

date_format: "%-d %B %Y"
