
#remote_theme: pages-themes/leap-day@v0.2.0
remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
- jekyll-remote-theme 
- jekyll-paginate
- jekyll-sitemap

language: fr

title: Gwada Paddling
subtitle: Actu des compétitions des sports de pagaie en Guadeloupe

post_search: true

social-network-links:
  rss: true
  
rss-description: Actu des compétitions des sports de pagaie en Guadeloupe

share-links-active:
  twitter: true
  facebook: true

date_format: "%-d/%m/%Y"

navbar-col: "#023047"
navbar-text-col: "#FFB703"
navbar-border-col: "#8ECAE6"
page-col: "#FFFFFF"
text-col: "#023047"
link-col: "#FB8500"
hover-col: "#219EBC"
footer-col: "#FB8500"
footer-text-col: "#023047"
footer-link-col: "#FFB703"
footer-hover-col: "#8ECAE6"
